export interface IImportHierarchy {
    Id: number,
    FunctionalLoc: string,
    Description: string,
    ConstType: string,
    MainWorkCtr: string,
    Plannergroup: string,
    Planningplant: string,
    MaintPlant: string,
    CostCenter: string,
    Sortfield: string,
    SupFunctLoc: string,
    Objecttype: string,
    Systemstatus: string,
    CreatedOn: string,
}